# Generated by Django 3.2.12 on 2022-07-08 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatlog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatlog',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='chatlog',
            old_name='user_id',
            new_name='user',
        ),
    ]
