# Generated by Django 3.2.12 on 2022-07-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatlog', '0002_auto_20220708_2246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatlog',
            old_name='answer_id',
            new_name='sent_answer',
        ),
        migrations.RenameField(
            model_name='chatlog',
            old_name='question',
            new_name='sent_question',
        ),
        migrations.AddField(
            model_name='chatlog',
            name='user_text_recived_body',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
